import { jsPDF } from 'jspdf';
import { toPng } from 'html-to-image';

export const generateTextSummary = (report: any): string => {
  const analysis = report.analysis || {};
  const diagnosis = analysis.potential_diagnosis_guess || report.potential_diagnosis_guess || 'Medical Report';
  const summary = analysis.holistic_summary || report.holistic_summary || report.summary || '';
  const explanation = analysis.easy_explanation || '';
  const keyFindings = analysis.key_findings || [];
  const healthInsights = analysis.health_insights || [];
  const dietToEat = analysis.diet_recommendations?.to_eat || [];
  const dietToAvoid = analysis.diet_recommendations?.to_avoid || [];
  const precautions = analysis.precautions || [];
  const nextSteps = analysis.next_steps || [];
  
  let text = `🏥 *RXDecode AI: Medical Analysis Report*\n\n`;
  text += `*Diagnosis Guess:* ${diagnosis}\n`;
  text += `*Summary:* ${summary}\n\n`;
  
  if (explanation) {
    text += `*Simple Explanation:* ${explanation}\n\n`;
  }

  if (keyFindings.length > 0) {
    text += `🔍 *Key Findings:*\n`;
    keyFindings.forEach((f: string) => text += `- ${f}\n`);
    text += `\n`;
  }

  if (healthInsights.length > 0) {
    text += `💡 *Health Insights:*\n`;
    healthInsights.forEach((i: string) => text += `- ${i}\n`);
    text += `\n`;
  }
  
  if (dietToEat.length > 0 || dietToAvoid.length > 0) {
    text += `🥗 *Dietary Recommendations:*\n`;
    if (dietToEat.length > 0) {
      text += `*To Eat:*\n`;
      dietToEat.forEach((d: any) => text += `- ${d.food}: ${d.benefit}\n`);
    }
    if (dietToAvoid.length > 0) {
      text += `*To Avoid:*\n`;
      dietToAvoid.forEach((d: any) => text += `- ${d.food}: ${d.reason}\n`);
    }
    text += `\n`;
  }

  if (precautions.length > 0) {
    text += `⚠️ *Precautions:*\n`;
    precautions.forEach((p: string) => text += `- ${p}\n`);
    text += `\n`;
  }

  if (nextSteps.length > 0) {
    text += `👣 *Next Steps:*\n`;
    nextSteps.forEach((s: string) => text += `- ${s}\n`);
    text += `\n`;
  }
  
  text += `_Generated by RXDecode AI Medical Assistant_`;
  return text;
};

export const downloadPDF = async (elementId: string, fileName: string) => {
  const element = document.getElementById(elementId);
  if (!element) return;

  try {
    // Use toPng to capture the element as an image
    // We use high quality and pixel ratio for a professional, sharp look
    const dataUrl = await toPng(element, {
      quality: 1.0,
      pixelRatio: 2,
      backgroundColor: '#ffffff',
      cacheBust: true,
      style: {
        borderRadius: '0',
        margin: '0',
      }
    });
    
    const img = new Image();
    img.src = dataUrl;
    await new Promise((resolve) => (img.onload = resolve));
    
    // A4 width is 210mm. We calculate height to maintain aspect ratio.
    const pdfWidth = 210;
    const imgHeight = (img.height * pdfWidth) / img.width;
    
    // Create a PDF with a custom page size that fits the entire content on one page
    // This prevents text and cards from being cut in half between pages, 
    // which is essential for a professional medical report.
    const pdf = new jsPDF({
      orientation: 'p',
      unit: 'mm',
      format: [pdfWidth, imgHeight],
      compress: true
    });
    
    pdf.addImage(dataUrl, 'PNG', 0, 0, pdfWidth, imgHeight, undefined, 'SLOW');
    pdf.save(`${fileName}.pdf`);
  } catch (error) {
    console.error('PDF generation failed:', error);
  }
};

export const shareReport = async (report: any) => {
  const text = generateTextSummary(report);
  const title = `Medical Report: ${report.potential_diagnosis_guess || 'Analysis'}`;
  
  if (navigator.share) {
    try {
      await navigator.share({
        title,
        text,
      });
    } catch (error) {
      console.error('Sharing failed:', error);
      copyToClipboard(text);
    }
  } else {
    copyToClipboard(text);
  }
};

const copyToClipboard = (text: string) => {
  navigator.clipboard.writeText(text).then(() => {
    // We don't use alert() in iframes, so we'll just log it or rely on the UI to show success
    console.log('Report summary copied to clipboard!');
  }).catch(err => {
    console.error('Clipboard copy failed:', err);
  });
};
